### PR TITLE
Fiximagehandlersaga

### PR DESCRIPTION
**Pull request by robbyxp1**
A few replaces to pick up the file characters

### CODE REVIEW

**Comment by finwen** [comment]
Resolves #108 
Resolves #38

**Comment by mwerle** [comment]
Any particular reason this just got closed and not merged?  I've got it in my personal build so will be testing it tonight anyway.. but curious.

**Comment by robbyxp1** [comment]
I for one did not close it.. Why was it closed? It works, I'm using it now in my own build.

**Comment by finwen** [comment]
Hmm did i miss to merge it then :)

**Comment by finwen** [comment]
I did add this manually.  Sorry for the miss :)

**Comment by robbyxp1** [comment]
Cheers.

On a general note, since I'm new to Git, best if someone else merges in my commits for now.. Still getting the hang of it, used to CVS/SVN 

Rob

**Comment by finwen** [comment]
Just do a pullrequst like you did now and i will hopefulle remember to merge it :)

**Comment by mwerle** [comment]
And, incidentally, I can (finally) confirm that it works. Was too tired last night to keep going to SagA after reaching WP11, and most of this morning I was stuffing about with various things.

Thanks for the fix, Rob :)

**Comment by robbyxp1** [comment]
No problem. I have a further fix/enhancement to the image part
    coming tomorrow.
    
    On 20/02/2016 14:13, Michael Werle
      wrote:
    
    
      And, incidentally, I can (finally) confirm that it works. Was
        too tired last night to keep going to SagA after reaching WP11,
        and most of this morning I was stuffing about with various
        things.
      Thanks for the fix, Rob :)
      —
        Reply to this email directly or view
          it on GitHub.

**Pull request closed without merging**
