### PR TITLE
make datetime filter in organic scans panel respect display time setting

### PR DESCRIPTION
**Pull request by RadarCZ**

### CODE REVIEW

**Comment by Eahlstan** [comment]
I see your point (I got an event happening shortly before midnight UTC that is on the next day in local time that doesn't show when selecting the local event day), but I think simply changing line 278 to

`orglist = orglist.Where(x => (start == null || x.Item2.EventTimeLocal >= start) && (end == null || x.Item2.EventTimeLocal <= end)).ToList();`

is:
- easier
- resembles the way other panels compare the event time
- does the same

I might be wrong and blind to see other effects your change has though.

**Comment by RadarCZ** [comment]
My change was supposed to make even the inputs (on the organics panel) show DateTime in a format I choose in the settings. Gonna look into your suggested change though.

**Comment by robbyxp1** [comment]
RadarCZ is right, because its better to store the value in the DB in UTC, and only display it in local..  thats so it works better over a daylight saving or change in TZ

**Comment by Eahlstan** [comment]
Always nice to learn more 🙃

**Comment by robbyxp1** [comment]
I'll pull this in later, thanks for the PR

**Comment by RadarCZ** [comment]
And feel free to edit the version number, since the releases use standard SemVer, but C# has 4 numbers, which I probably also misused :D
Thanks for the notice

**Comment by Eahlstan** [comment]
> And feel free to edit the version number, since the releases use standard SemVer, but C# has 4 numbers, which I probably also misused :D Thanks for the notice

It's more the pushed .gitmodules I'm worried to get pulled in, can you add that to your gitignore so you don't PR this in the future?

**Comment by RadarCZ** [comment]
Now that i think about it, it doesn't really makes sense to be pushed, thanks for the "kick". Will fix right now!

**Comment by robbyxp1** [comment]
I'll fix this in the same manner as all other panels.   So the current code is now wrong.

Pushing code down to the lower levels when they don't need to know about the upper level ideas of being able to handle date time pushed is not correct.  Handling the variations of date time is a EDD project level problem.

**Comment by robbyxp1** [comment]
Thanks. Let me fix it, i have all the code to fix it in my mind.

**Comment by RadarCZ** [comment]
Alright then, closing this.

**Pull request closed without merging**
