### PR TITLE
Fiximagehandler

### PR DESCRIPTION
**Pull request by robbyxp1**
Fix the image handler..

Fix the problem with deleting the file.

Hopefully this is right

### CODE REVIEW

**Comment by robbyxp1** [comment]
Try this, this looks good..

**Comment by gregmalcolm** [comment]
Woot!

**Comment by robbyxp1** [comment]
;-) Bit confusing for an old git like me.. I'll read up more about how GIT works.

**Comment by gregmalcolm** [comment]
Fixes #74

**Comment by gregmalcolm** [comment]
Just checked over the code. I'll let someone more familiar with this aspect of the code decide whether or not to merge it, but looks fine to me.

**Comment by robbyxp1** [comment]
i did a lot of testing on it today, and the problem disappeared. As I said in the previous post, the documentation states that the file is locked until the resource is deallocated. So we need an explicit call to force it to unlock the file.  The last bit is a nicety and it provides a visual confirmation the screenshot was converted.

**Comment by finwen** [comment]
Looks good.  Will merge and test.

**Pull request merged**
