### PR TITLE
Add IGAU classes

### PR DESCRIPTION
**Pull request by Elite-IGAU**
Mostly copy/paste from EGO class to start.

TODO:

Set journal scan code to look for "CodexEntry" lines most of EGO stuff is not needed.

Configure HTTP POST routine to send "timestamp", "name_localised", and "system" in JSON format.

### CODE REVIEW

**Comment by Elite-IGAU** [comment]
This shouldn't break anything in the codebase - pretty much a simple copy/paste from the EGOclass.cs and EGOsync.cs files.  

I think most everything in EGOSync.cs can be tossed. Seems to do way more than what is needed for IGAU's purposes. 


Really only need code similar to this ( from Elite Observatory ) - wonder if this can all be in IGAUclass.cs? (and remove IGAUsync.cs?) 

if (SyncToIGAU)
                  {
                  JObject POST_content = JObject.FromObject(
                new {
                    timestamp = codexEntry.Timestamp.ToString("yyyy-MM-ddTHH:mm:ssZ"),
                    Name_Localised = codexEntry.NameLocalised,
                    codexEntry.System
                });
                  var request = new System.Net.Http.HttpRequestMessage
                   {
                        Method = HttpMethod.Post,
                        RequestUri = new Uri($"https://ddss70885k.execute-api.us-west-1.amazonaws.com/Prod"),
                        Content = new StringContent(POST_content.ToString(Formatting.None))
                   };
                   HttpClient.SendRequest(request);
                  }

**Comment by Elite-IGAU** [comment]
Also, when I attempt to build, this error comes up:

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS2001	Source file 'D:\code\EDDiscovery\EDDiscovery\Properties\ExtraVersion.cs' could not be found.	EDDiscovery	D:\code\EDDiscovery\EDDiscovery\CSC	1		Active

**Comment by klightspeed** [comment]
ExtraVersion.cs should be generated by the `Version` target in EDDiscovery.csproj, which it included both in DefaultTargets and as a `BeforeTarget` to `Build`.  It sounds like your build system is ignoring both of these.

As a workaround, you can create an empty `ExtraVersion.cs` file.

**Comment by Elite-IGAU** [comment]
I'm using Visual Studio 2019 - community edition.  Will Add an empty file, however it will try to track in GitHub.

**Pull request closed without merging**
