### PR TITLE
Refactor UserControlJournalGrid for Performance and Maintainability

### PR DESCRIPTION
**Pull request by BartonsGit**
## Shortnotes:
- Implement EnumerableExtensions for efficient data chunking
- Modularize initialization and event handling in UserControlJournalGrid
- Optimize Display method for better performance with large data sets
- Improve code quality with modern C# practices and reduce duplication
- Enhance user experience with UI improvements and clearer feedback
- Strengthen security and reliability through better error handling

---

# Patch Notes for UserControlJournalGrid.cs

## Enhancements

- Added `EnumerableExtensions` class with a `ChunkBy` method to efficiently handle large sets of data by dividing them into manageable chunks.
- Introduced a more structured and modular approach to initializing the `UserControlJournalGrid` by breaking down the initialization process into smaller, more focused methods such as `SetupDataGridView`, `SetupFilterSelector`, `SetupTimers`, and `SubscribeToEvents`.
- Improved the handling of the `Display` method to support chunk processing of history entries for better performance and responsiveness.
- Enhanced event handling with more granular methods for specific actions, improving readability and maintainability.
- Added detailed XML documentation comments to methods and classes for better understanding and maintainability of the code.
- Refactored various parts of the code to use more modern C# features and practices, improving readability and performance.
- Improved error handling and user feedback for operations that interact with external systems or files, such as exporting data.

## Fixes

- Fixed potential issues with event subscription that could lead to memory leaks or unexpected behavior by changing delegates to events.
- Addressed potential inefficiencies in data processing and UI updates, particularly in methods handling large volumes of data.
- Corrected and standardized the handling of UI elements' state and visibility, ensuring a consistent user experience.

## Code Quality Improvements

- Consolidated similar code blocks and extracted them into reusable methods to reduce duplication and improve maintainability.
- Adopted a more consistent coding style across the file, including the use of var where appropriate, simplifying conditional statements, and improving method naming conventions.
- Removed unused variables and streamlined data handling to improve performance and reduce memory footprint.
- Enhanced the readability of the code by organizing methods logically and adding region markers for better navigation.

## User Experience Enhancements

- Improved the responsiveness of the UI during long-running operations by implementing chunk processing and optimizing data grid view updates.
- Added more descriptive tooltips and error messages to provide users with clearer information and guidance.
- Refined the user interface layout and behavior to be more intuitive and user-friendly, particularly in handling user inputs and displaying data.

## Security and Reliability

- Strengthened input validation and error handling to prevent potential crashes or unexpected behavior, especially in file operations and external data interactions.

## Miscellaneous

- Updated XML documentation comments to reflect changes and provide comprehensive information on methods and their purposes.
- Minor adjustments and optimizations to improve the overall performance and stability of the application.

### CODE REVIEW

**Comment by Eahlstan** [comment]
Applying this crashes EDD when trying to open a new Journal panel.

```
System.Resources.MissingManifestResourceException
  HResult=0x80131532
  Message=Für die angegebene Kultur oder die neutrale Kultur konnten keine Ressourcen gefunden werden. Stellen Sie sicher, dass EDDiscovery.UserControls.UserControlJournalGrid.resources beim Kompilieren richtig in die Assembly EDDiscovery eingebettet wurde, oder dass die erforderlichen Satellitenassemblys geladen werden können und vollständig signiert sind.
  Source=mscorlib
  StackTrace:
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at EDDiscovery.UserControls.UserControlJournalGrid.InitializeComponent() in F:\Git\EDDiscovery\Original\EDDiscovery\EDDiscovery\UserControls\History\UserControlJournalGrid.Designer.cs:line 329
   at EDDiscovery.UserControls.UserControlJournalGrid..ctor() in F:\Git\EDDiscovery\Original\EDDiscovery\EDDiscovery\UserControls\History\UserControlJournalGrid.cs:line 114
```
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Ein Aufrufziel hat einen Ausnahmefehler verursacht.
  Source=mscorlib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at EDDiscovery.PanelInformation.Create(PanelIDs p) in F:\Git\EDDiscovery\Original\EDDiscovery\EDDiscovery\TabsPanelsAndPopOuts\Panels.cs:line 333
   at EDDiscovery.MajorTabControl.CreateTab(PanelIDs ptype, String name, Int32 dn, Int32 posindex, Boolean primary) in F:\Git\EDDiscovery\Original\EDDiscovery\EDDiscovery\TabsPanelsAndPopOuts\MajorTabControl.cs:line 271
   at EDDiscovery.MajorTabControl.AddTab(PanelIDs id, Int32 tabindex) in F:\Git\EDDiscovery\Original\EDDiscovery\EDDiscovery\TabsPanelsAndPopOuts\MajorTabControl.cs:line 154
   at EDDiscovery.EDDiscoveryForm.AddTab(PanelIDs id, Int32 tabindex) in F:\Git\EDDiscovery\Original\EDDiscovery\EDDiscovery\EDD\EDDiscoveryFormTabs.cs:line 32
   at EDDiscovery.UserControls.UserControlPanelSelector.ButtonPress(Object o, Int32 i) in F:\Git\EDDiscovery\Original\EDDiscovery\EDDiscovery\UserControls\GridsSplitters\UserControlPanelSelector.cs:line 174
   at ExtendedControls.CompositeAutoScaleButton.<>c__DisplayClass16_0.<QuickInit>b__0(Object o, EventArgs e) in F:\Git\EDDiscovery\Original\EDDiscovery\ExtendedControls\ExtendedControls\Controls\CompositeAutoScaleButton.cs:line 142
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at ExtendedControls.ExtButton.OnMouseUp(MouseEventArgs mevent) in F:\Git\EDDiscovery\Original\EDDiscovery\ExtendedControls\ExtendedControls\Controls\Button.cs:line 249
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at EDDiscovery.Program.Main() in F:\Git\EDDiscovery\Original\EDDiscovery\EDDiscovery\Program.cs:line 36

  This exception was originally thrown at this call stack:
    System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(string)
    System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary<string, System.Resources.ResourceSet>, bool, bool, ref System.Threading.StackCrawlMark)
    System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, bool, bool, ref System.Threading.StackCrawlMark)
    System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, bool, bool)
    System.Resources.ResourceManager.GetObject(string, System.Globalization.CultureInfo, bool)
    EDDiscovery.UserControls.UserControlJournalGrid.InitializeComponent() in UserControlJournalGrid.Designer.cs
    EDDiscovery.UserControls.UserControlJournalGrid.UserControlJournalGrid() in UserControlJournalGrid.cs

Inner Exception 1:
MissingManifestResourceException: Für die angegebene Kultur oder die neutrale Kultur konnten keine Ressourcen gefunden werden. Stellen Sie sicher, dass EDDiscovery.UserControls.UserControlJournalGrid.resources beim Kompilieren richtig in die Assembly EDDiscovery eingebettet wurde, oder dass die erforderlichen Satellitenassemblys geladen werden können und vollständig signiert sind.
```

Which might be related to the warning given on building:

`12>F:\Git\EDDiscovery\Original\EDDiscovery\EDDiscovery\UserControls\History\UserControlJournalGrid.cs(86,29,86,37): warning CS0067: The event 'UserControlJournalGrid.OnPopOut' is never used`

**Comment by BartonsGit** [comment]
The problem seems to be stemming from attempting to apply translations. Commenting out the lines 329 and 343 on the UserControlJournalGrid designer allows the journal to act as normal. (Minus the arrow in the textbox, and the tooltip)

```cs
EDDiscovery\UserControls\History\UserControlJournalGrid.Designer.cs
329 ----> this.textBoxSearch.EndButtonImage = ((System.Drawing.Image)(resources.GetObject("textBoxSearch.EndButtonImage")));
343 ----> this.toolTip.SetToolTip(this.textBoxSearch, resources.GetString("textBoxSearch.ToolTip"));
```

Need to look into the translation engine a little more.

**Comment by BartonsGit** [comment]
@Eahlstan - Crash _should_ be resolved now. Thank you for getting feedback so quickly.

**Comment by robbyxp1** [comment]
Thanks for the push, but I'm not going to bring it in now. I'll have a look at it much later, I have a backlog of stuff to do and adding risk like a large refactor like this i'm not interested in.

Moved to workflow

**Comment by BartonsGit** [comment]
@robbyxp1
I completely understand your concerns regarding the risk associated with merging a significant refactor at this time.

Thank you for your feedback and for considering the pull request.

**Pull request closed without merging**
