### PR TITLE
Add level field to ScanNode

### PR DESCRIPTION
**Pull request by klightspeed**
This should help @andreaspada simplify #1387

### CODE REVIEW

**Comment by andreaspada** [comment]
Awesome! Thank you so much! I'll rewrite my code using such an improvement! I knew it could be done in a more elegant way... KUDOS!

**Comment by andreaspada** [comment]
Hi, @klightspeed 

Just included your code in my branch, and used your suggestion, however it give me such errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'level' does not exist in the current context	EDDiscovery	D:\Users\andrea\Development\GitHub\EDDiscovery\EDDiscovery\UserControls\UserControlStarList.cs	278	Active
Error	CS0103	The name 'type' does not exist in the current context	EDDiscovery	D:\Users\andrea\Development\GitHub\EDDiscovery\EDDiscovery\UserControls\UserControlStarList.cs	278	Active
Error	CS0103	The name 'ScanNodeType' does not exist in the current context	EDDiscovery	D:\Users\andrea\Development\GitHub\EDDiscovery\EDDiscovery\UserControls\UserControlStarList.cs	278	Active
```

I'm certainly didn't understand how to refer to the new level. I substituted my regex with your statement:

if (level >= 2 && type == ScanNodeType.body) {
code here...
} 

Can you give me a clue? I'm still learning, a very small step a time...

**Comment by klightspeed** [comment]
```
if (sn.level >= 2 && sn.type == StarScan.ScanNodeType.body){
    ...
}
```

**Comment by andreaspada** [comment]
Love you! lol

**Comment by andreaspada** [comment]
It's a perfect solution, cause it catch also bodies with curious or non-standard names. KUDOS!

**Comment by klightspeed** [comment]
This is now part of #1392

**Pull request closed without merging**
