### PR TITLE
Igau dialog

### PR DESCRIPTION
**Pull request by Elite-IGAU**
I've added in the dialogs, and the IGAUClass.cs - largely based on the now defunct EGOClass. 
Project builds, loads, and runs fine. 

TODO:  

1.) Figure out how to only run function in IGAUClass.cs if the IGAU checkbox is selected in CMDR settings window

2.) Strip "$" , "_Name", and ";" from journal CodexEntry line field "Name", and convert to lower case.
Examples: 
$Codex_Ent_SeedEFGH_Name; should be codex_ent_seedefgh 
$Codex_Ent_SeedEFGH_01_Name; should be codex_ent_seedefgh_0
$Codex_Ent_Fumarole_SulphurDioxideMagma_Name; should be codex_ent_fumarole_sulphurdioxidemagma

3.) Update App_Name and App_Version with EDDiscovery's own "global" variables for the application name and version.

Should be a few relatively minor changes/tweaks to get this into the main codebase.

### CODE REVIEW

**Comment by spadino** [comment]
Awesome, many thanks!

**Comment by Elite-IGAU** [comment]
I think somewhere in IGAUClass.cs to rewrite "Name" from the journal, it would be something like?

Name = JournalScan.Entry.Name
.Replace("$", string.Empty)
.Replace("_Name", string.Empty)
.Replace(";", string.Empty)

Not sure about switching it all into lower case. (see above examples) 

I was also told that "ProductVersion" is a variable that can be used in Windows apps. 

Let us know if you have any questions. You are welcome to hop on our Discord: 
https://discord.gg/2Qq37xt

**Comment by klightspeed** [comment]
The version used everywhere in EDDiscovery is the assembly version of the `EDDiscovery.exe` executable (which gets exposed as the file version).

The assembly informational version (which contains the commit from which it was built) is exposed in the Product Version.

--------------------

For the assembly version:

EDDN uses:
```cs
var assemblyFullName = Assembly.GetEntryAssembly().FullName;
var version = assemblyFullName.Split(',')[1].Split('=')[1];
```

There is also:
```cs
var version = Assembly.GetEntryAssembly().GetVersionString();
```
`Assembly.GetVersionString` is an extension method which is defined in BaseUtils, and essentially uses:
```cs
var version = new AssemblyVersion(Assembly.GetEntryAssembly().FullName).Version.ToString();
```

--------------------

If you want `AssemblyInformationalVersion` as defined in `ExtraVersion.cs` (-> Product Version - i.e. you want to know what commit EDDiscovery was built from), you can use:
```cs
var version = Assembly.GetEntryAssembly().GetCustomAttribute<AssemblyInformationalVersionAttribute>().InformationalVersion;
```

**Comment by Elite-IGAU** [comment]
I'm honestly not that picky on what version number, or method used to set the variable. Appreciate the in-depth response though!

**Comment by Elite-IGAU** [comment]
@robbyxp1 - quick question - the way your code interprets EntryID, SystemAddress and the Version Number - would those try to parse out as integers or strings? Might have to make a quick update to ensure they are sent as strings, since that's what the API endpoint is expecting.

**Comment by klightspeed** [comment]
For codex events, `SystemAddress` and `EntryID` are long integers (Int64).

You don't appear to have committed the code you're talking about when you say you might have to ensure they are sent as strings, as your `CreateIGAUMessage` already requires these be strings, and I see nothing calling `CreateIGAUMessage`.

**Comment by Elite-IGAU** [comment]
@klightspeed - Yes, Basically what is here is "here's what I've got" along with a small request for assistance clarification, since I'm not familiar with the EDDiscovery codebase. Additionally, I'm more of a Python dev than a C/C# dev. 

The first of the items in the TODO - I'm not sure how in the code to kick off the code in IGAUClass.cs , based on whether or not the "Send to IGAU" check box is clicked.  I know the EGO code is largely removed/defunct, however if you could point me to it, I might be able to figure it out on my own. 

Worst case, someone who knows the code base might be able to spend ten or fifteen minutes and assist me with the last few issues before this should be acceptable to merge into the code base, or at the very least a branch for testing.

**Comment by robbyxp1** [comment]
I'll bring this code in and fix it up next week so at least its all wired up to the IGAU class level.

**Comment by Elite-IGAU** [comment]
As always, I (and the IGAU) appreciate you lending a hand with this. 

If you have any questions, or need to pitch a branch back to me for more work, holler at me on the IGAU discord.  Also, if you run this internally and test data shipments to us, also give me a holler and I can confirm entries in our database. 


> I'll bring this code in and fix it up next week so at least its all wired up to the IGAU class level.

**Pull request merged**
