### PR TITLE
Add perspective rendering on 3D map

### PR DESCRIPTION
**Pull request by klightspeed**
This adds the option for perspective rendering as an alternative to the current orthogonal rendering.

This was proposed in #116

This also maps Right-drag to Y-axis translation, and Left+Right-drag to panning on the X and Z axes.

### CODE REVIEW

**Comment by gregmalcolm** [comment]
My experience with working on the rendering sequence has taught me that the matrix transformation can be tricksy. I'll ackknowledge there was a bug with mouse drag after rotating the map already that I never got around to fixing it, but...

Can you confirm that moving the map around with the WASD keys still works? Even if the map is rotated and zoomed?

**Comment by klightspeed** [comment]
`W` moves the focused point "up" from the camera's perspective, which is North when unrotated.
`S` moves the focused point "down" from the camera's perspective, which is South when unrotated.
`A` moves the focused point to the camera's left, which is West when unrotated.
`D` moves the focused point to the camera's right, which is East when unrotated.

`R` and `F` seem to be swapped - `R` goes rearwards, and `F` goes forwards, while the names of the actions suggest they should do the opposite.

These work correctly with respect to the rotation and zoom of the camera.  Zooming in the camera slows down the movement, and zooming out the camera speeds it up.  Motion is along the left/right/up/down/forward/back axes according to the camera's perspective.

Pitch up and down raises and lowers the camera's lattitude above / below the point.
Roll left and right rotates the map along its Y axis.
Yaw left and right is dependent on the pitch and roll.

**Comment by gregmalcolm** [comment]
As long as the movement keys work in combination is the main thing. When the transformation sequence is bad movement becomes wierd... :)

Another gotcha is keeping the Y axis pointing the right way. I guess if you check that the DW path is ascending at Sag A rather than descending you're in the clear

**Comment by klightspeed** [comment]
I did indeed check that the DW path at Sagittarius A* ascended, which is why I added 18a41ee.

For the camera Y, a quick fix might be to negate Y on line 149 of `FormMap.cs`, and negate it again when displaying the coordinates.

**Pull request merged**
