### PR TITLE
Process white dwarf star types from EDSM properly

### LINKED ISSUE #1965: Support for White Dwarf (DAZ) Star type
On visiting system LHS 1547, EDSM correctly lists LHS 1547 A as a White Dwarf (DAZ) Star, whilst EDDiscovery simply lists unknown star.

### PR DESCRIPTION
**Pull request by klightspeed**
This should fix #1965

### CODE REVIEW

**Comment by robbyxp1** [comment]
After our EDSM crash this week, i'd be tempted to check start >=0 as well.. if start = -1, you end up adding 1 to len..

**Comment by klightspeed** [comment]
If start == -1, then that'd mean that either `StartsWith` has a bug, or the CPU is faulty.

**Comment by klightspeed** [comment]
Checked, and `StringComparison.InvariantCultureIgnoreCase` does not match any character to `(` other than itself.

**Comment by robbyxp1** [comment]
Cheers

**Pull request merged**
