### PR TITLE
#2345 mapped column in estimated values

### PR DESCRIPTION
**Pull request by carcher99**
Added Body Type and Mapped columns to the Estimated Values panel. Response to the feature request #2345 in the Projects - Future Ideas page

### CODE REVIEW

**Comment by robbyxp1** [comment]
Okay, but if we are going to do this, why not also have a column showing if the body has been discovered?

**Comment by carcher99** [comment]
Sure I can add that

**Comment by carcher99** [comment]
..but thinking about it - if it is in estimated values list surely that implies it's discovered...what am i missing?

**Comment by klightspeed** [comment]
> ..but thinking about it - if it is in estimated values list surely that implies it's discovered...what am i missing?

I think Robby means whether `WasDiscovered` is true on the scan, meaning that the body has been "tagged" by somebody else.

**Comment by carcher99** [comment]
> I think Robby means whether `WasDiscovered` is true on the scan, meaning that the body has been "tagged" by somebody else.

Thanks - I'll get that done.

**Comment by robbyxp1** [comment]
Yes, WasDiscovered, WasMapped..

**Comment by carcher99** [comment]
Done - Obviously open to feedback gents.

**Comment by robbyxp1** [comment]
thanks

**Pull request merged**
