### PR TITLE
Don't leave the body until LeaveBody

### PR DESCRIPTION
**Pull request by klightspeed**
This should fix incorrect distances shown in the Compass while in orbital cruise, after entering supercruise.

### CODE REVIEW

**Comment by robbyxp1** [comment]
Looks good, why do we need to fix it up on undocking?  Is that just for completeness?

**Comment by klightspeed** [comment]
`ApproachBody` is not logged when the commander logs in docked to a planetary outpost, nor is it logged when we undock from said outpost.

**Comment by robbyxp1** [comment]
Thanks.  I was wondering more about the dictionary.. which makes the class have a memory, where it did not have one before.  Which is not ideal.

So I get that we want to restore the state we had before docking (whereami/bodytype).  I've been thinking of a way to do it without memory but i can't see one either.

Would not just a record of these two parameters, written on dock, be enough to restore it?  Could that dictionary get large on very large data sets (being memory paranoid)? Do we need the dictionary of market ids to guarantee restore?..

Hmmm..

Anyway i'll incorporate this in for now. thanks.

**Comment by robbyxp1** [comment]
Some comments..

HES constructor not copying StarPos?  StarPos? is not in use.
Constructor not copying SystemAddress..  SystemAddress is not in use

Need a little tlc ;-)

**Comment by robbyxp1** [comment]
I've taken a branch and fixed up a few issue i saw when it processed my history on this new branch.

I've also simplified a few things, such as having an enum for travel state, and removing some fields..

will check and post a new PR

**Pull request closed without merging**
