### PR TITLE
Some fixes for Plot and Map

### PR DESCRIPTION
**Pull request by andreaspada**
- Fixed mouseenter/leave switch for pan; 
- fixed menu for plot; 
- fixed axis designement in Plot;
- added a combobox for change views, undocked;
- undocked the slide on Map and positioned it beside other controls.

### CODE REVIEW

**Comment by andreaspada** [comment]
I merged with 9.1.5.

**Comment by andreaspada** [comment]
@robbyxp1, there are some important bug fixes here. It should be included on next minor release (9.1.6...)

**Comment by robbyxp1** [comment]
You left warnings in.. I will fix it
9>C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlPlot.cs(462,17,462,51): warning CS0252: Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'string'
9>C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlPlot.cs(468,17,468,53): warning CS0252: Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'string'
9>C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlPlot.cs(474,17,474,52): warning CS0252: Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'string'

**Comment by robbyxp1** [comment]
SelectedItem returns an object.. not a string. you can assign more than a string to a combobox item

**Comment by robbyxp1** [comment]
Also some comments.. see this..
 private void toolStripMenuZoom125_Click(object sender, EventArgs e)
etc in LocalMap.  Now if you would have used the Tag on each of the toolStipMenuZoom's, and assigned an float to the tag
toolStripMenuZoom125.Tag = 1.25

then all the tool strip clicks could have pointed to one function, and you could have found the zoom it wanted by:

double zoom = (double)((Control)sender).Tag;

**Comment by robbyxp1** [comment]
The other way of course is to get their text and use 
string front = control.Text.Substring(0,control.text.Indexof(control.text,":"))
double d = front.InvariantParseDouble()

Always use the parsers in numberobjectextensions please.. they are safe from exceptions.  ParseXNull is very useful

double? d = string.InvariantParseDoubleNull() returns null if its no good, or the value

**Comment by andreaspada** [comment]
Thank you so much, @robbyxp1! Your comments are always more than welcome. I understand that my coding style is, well, quite primitive, especially when analyzed by some bad-ass coder like you. There are so many things I still do not comprehend: that "tag", btw, is something I really did not got clearly, and never remember to try to use it. Your explanation, finally, pointed me to the right direction.

You are absolutely right! Using a Tag as you suggested clean up the code so much. You are amazing!

**Pull request merged**
