### PR TITLE
Chinese Translation + Translation improvement

### PR DESCRIPTION
**Pull request by Nats-ji**
Added Chinese Translation.
Made notify menu translatable.
Added some missing spots for translation on some forms and user controls.
Added function for displaying the language names on the settings panel instead of file name.
Added translation ids for theme editor(see pull request on [extentedcontrols](https://github.com/EDDiscovery/ExtendedControls/pull/12#issue-257567716) ) in the translation files.
Added translation support for about form.
Fixed formatting on trip computer overlay.

I'm still working on improving the translatability of this program.
Will update the translation IDs on the translation files later.
I'm new to C# there might be some bugs xD

### CODE REVIEW

**Comment by spadino** [comment]
That's fantastic, thank you so much! A Chinese translation it's a big feature, for sure, and your work on the extended control are much appreciated. ;)
Welcome to the translator team!

**Comment by spadino** [comment]
@Nats-ji, are you on Discord? If not, join our translator channel! https://discord.gg/MB2mg9

**Comment by robbyxp1** [comment]
Thanks for this, but this is way too big to bring in at the moment. you've changed lots of executables, not just the translation files.  i would have to triage all of them.

i suggest we pend this until the master is reopened for new code, which won't be until the start of april

**Comment by robbyxp1** [comment]
But will bring it in then.

**Comment by Nats-ji** [comment]
Sure. Then I will open another pull only for the translation files.

**Comment by robbyxp1** [comment]
Okay, or you can wait..

I organise the releases into two major periods.. updates, then release and fix.  As 10.5 we are in a release and fix phase.  As I'm out of action for the last two weeks of march this period will be most of march.

**Comment by Nats-ji** [comment]
It's ok. I will just this one here. I'm stilling working on the codes.
I opened another one only for the translations.

**Comment by robbyxp1** [comment]
So, i've pulled the other one in, and moved the files to their correct location. Suggest you do another PR later with any code changes you need.

thanks

**Pull request closed without merging**
