### PR TITLE
New panel ScanGrid added

### PR DESCRIPTION
**Pull request by andreaspada**
Added a new panel, ScanGrid, which display the information of bodies scanned in a system in a grid, for an uncluttered and unobtrusive yet comprehensive view. Beside the body image, name and class, display some brief information, such as stellar mass and habitable zone, planets special state such as terraformable, ringed or volcanism and, for landable planets, it shows also the gravity.
Fields can be multiple selected, for easy copying and paste...

* More improvement planned, such as row coloring (if possible), available materials list and export, but the panel is already functional.

Modified the dataGridViewNearest name in the EstimatedValues panel to dataGridViewEstimatedValues, for better code understanding and naming convention; presumably, it was copied from the StarDistances panel.

### CODE REVIEW

**Comment by andreaspada** [comment]
For reasons I don't understand, even following the procedure the @phroggster explained to me, I'm not able to include the proper icon as a Resource. 
If someone else can do this for me, I'll be very thankful ;)

scangrid

**Comment by klightspeed** [comment]
Try putting it into the EDDiscovery/Resources directory, then open Properties/Resources.resx, select Images, and drag the png icon into the resx images

**Comment by andreaspada** [comment]
@klightspeed, I already did that. I don't really understand why is not working... as I have no experience with that, I'm quite stalled. However, I'll give it more chances.

**Comment by andreaspada** [comment]
Got it! I added scangrid.png to EDDiscovery resources, but I was referencing EliteDangerous resources. I'm  adding it to the PR.

**Comment by andreaspada** [comment]
Travis-ci do not see the icon, but Appveyour yes... weird?

**Comment by andreaspada** [comment]
Possibly, it's a case sensitive bug. I'll check and reopen the PR when ready.

**Comment by andreaspada** [comment]
Struggling with the Resource path. I fixed it in Resources.resx, yet refuse to compile in Travis-CI...

**Pull request closed without merging**
