### PR TITLE
Created Splits and Tabs UserControl containers; reordered panels list.

### PR DESCRIPTION
**Pull request by andreaspada**
Preliminary work for a generic user containers set.

- Splits: UserControl inside splitpanels
- Tabs: UserControl inside tabs

---

Splits has a context menu, which by now let the user choose the orientation.
Tabs is in process of implement the MajorTabControl context menu...

### CODE REVIEW

**Comment by robbyxp1** [comment]
I don't have time to look at the moment, i think this will need to wait until we are well past this 3.0 phase.

Please don't re-order the panel list again.. people are used to the order!

**Comment by andreaspada** [comment]
> Please don't re-order the panel list again.. people are used to the order!

Hahahahahaa!!!! Of course, sorry... ;)

**Comment by robbyxp1** [comment]
I'm going to close this. I don't have time to code review.  

You should also push a more incremental version of it, one bit and a time so its easier to digest.. such as a split container first.  

Also no embeded resource icons!

Thanks

**Comment by andreaspada** [comment]
Of course! ;)

**Pull request closed without merging**
