### PR TITLE
Bump nuget dependencies

### PR DESCRIPTION
**Pull request by phroggster**
* Fix EliteDangerous/app.config dependency redirect mishap.
* Retain older SharpDX, SharpDX.DirectInput, CSCore deps.

| Package | Old Version | New Version |
|-------------------|-------------|-------------|
| NFluent | 2.0.0 | 2.1.0 |
| NUnit | 3.7.1 | 3.9.0 |
| NUnit3TestAdaptor | 3.7.0 | 3.9.0 |
| SQLite.Core | 1.0.105 | 1.0.106 |
| SQLite.Linq | 1.0.105 | 1.0.106 |

### CODE REVIEW

**Comment by phroggster** [comment]
Hopefully the SQLite bumps will address #1523.

**Comment by klightspeed** [comment]
Except: https://www.virustotal.com/#/file/6c9c8c0fc85e5fbd214e8eb3e084136216b0f9c08b78bcc10318dcda8486c857/detection

**Comment by phroggster** [comment]
There's no telling whether that's the official package or not. In fact, it's not... https://www.virustotal.com/#/url/4c833a265547edb596df723e5f48890c145dbc2a7b96d3184efde833929e2c6b/detection was the portable zip that AppVeyor just generated.

**Comment by klightspeed** [comment]
Follow the "Downloaded file" link, and you get a different story...

**Comment by phroggster** [comment]
Yeah, you're right. I forget that Baidu isn't included in the URL scans. Is it time to just pack it directly as a resource into the portable executable? Not sure how to appease the Chinese AV maker that seems to think a database is a virus...

**Pull request merged**
