### PR TITLE
In-game stat tree stat saved reliably, Home System validation no longer prevents entry

### PR DESCRIPTION
**Pull request by iainross**

### CODE REVIEW

**Comment by robbyxp1** [comment]
Using leave is problamatic normally.. its not guaranteed someone will leave the control.  Its normally better to validate as they type, using text changed..

**Comment by robbyxp1** [comment]
I've removed quite a lot of leave validations for that reason..

**Comment by iainross** [comment]
Aye - that's why it does a check on closing as well.  The problem with Validated is that it was over-writing with the setting as you typed making it impossible to actually change it.

**Comment by robbyxp1** [comment]
i'll have a think if we can improvie it after i merge it in

**Pull request merged**
