### PR TITLE
Fix dotless i (\u0131)

### LINKED ISSUE #2095: Unicode Character 'LATIN SMALL LETTER DOTLESS I' (U+0131)
EDDiscovery v10.1.6.0 is using U+0131 for some commodity names.
see: https://ross.eddb.io/eddn/log/76905490

```
{
  "\u0131nsulatingmembrane",
  "neofabric\u0131nsulation",
  "heatsink\u0131nterlink",
  "\u0131ndium",
  "\u0131ndite"
}
```

### PR DESCRIPTION
**Pull request by klightspeed**
This should fix #2095

### CODE REVIEW

**Comment by robbyxp1** [comment]
Need to understand this more..

EDDNClass.cs sends fdname (389) to EDDN

        "data":"ındium",
        "message":"unknown commodity name"

where is this coming from?  Indium in materialcommds is okay - its an i.  fdname should not be localised?

**Comment by klightspeed** [comment]
It looks like Frontier is using `ToLower` to lowercase the commodity symbolic name.

**Comment by hchalkley** [comment]
I don't understand how the dotless i would get into the market.json, there's no tolower() applied to the string written out, and anyway Frontier's Cobra engine fToLower() method doesn't check locale, and only converts within the plain ascii range.
I have logged the issue as ED-99647 in our Jira database, but further evidence (such as a player journal or market.json fie) would help

**Comment by klightspeed** [comment]
Gah - it isn't Market.json, but rather https://github.com/EDDiscovery/EDDiscovery/blob/master/EliteDangerous/EliteDangerous/CommodityPrices.cs#L74

**Pull request merged**
