### PR TITLE
Moon declaration in Star List Panel Information summary

### PR DESCRIPTION
**Pull request by andreaspada**
Now, the Visited Star List Panel inform us if a body is a moon, alongside with it's special state.
So, for bodies lin a system Eol Prou ZZ-Z d99-9, it could inform us that:

Eol Prou ZZ-Z d99-9 A is a water world
Eol Prou ZZ-Z d99-9 A b is terraformable moon
Eol Prou ZZ-Z d99-9 B a 2 is an ammonia moon
etc...

### CODE REVIEW

**Comment by klightspeed** [comment]
Body designations follow the following scheme:

`<system> 1` is the first planetary body orbiting the main star in a single-star system
`<system> A` is a star in a multi-star system
`<system> A 1` is the first planetary body orbiting that star
`<system> A 1 a` is the first natural satellite of that planetary body
`<system> A 1 a b` is the second natural satellite of the above natural satellite

**Comment by klightspeed** [comment]
Since you're working on the bodies from the SystemNode, it shouldn't be too difficult to add a flag to ScanNode to indicate that it is level 2 (i.e. a natural satellite of a planetary body) or deeper.

**Comment by klightspeed** [comment]
#1390 adds a `level` field to the ScanNode, so if `level >= 2 && type == ScanNodeType.body`, then the body is a moon.

**Comment by klightspeed** [comment]
It might be a good idea to squash these commits, as temporary files in commits are frowned upon.

**Comment by andreaspada** [comment]
> It might be a good idea to squash these commits, as temporary files in commits are frowned upon.

Done!

**Pull request closed without merging**
