### PR TITLE
Use default directory if output dir is null

### LINKED ISSUE #917: Screenshots strangely stopped working after update - BUG
I just compiled the last git commitment and when I take a screenshots the following message appear:

`Error in executing image conversion, try another screenshot, check output path settings. (Exception Object reference not set to an instance of an object.)`

No setting were modified. I use the Commander/System organization. Tried also with other commanders, and others organization =, but all of them gave me such message.

How could be trace the problem?

### PR DESCRIPTION
**Pull request by klightspeed**
This should fix #917 in the case that the output directory field is empty.

### CODE REVIEW

**Comment by andreaspada** [comment]
This is driving me nut. I hadn't changed nothing in my setup, and it was working perfectly before some update. Still do not work.

I freshly create a new data, with all my CMDR, correctly displaying my history, journal and EDSM syncs. I'm using the very last build, from AppVeyor, the one which has been corrected from the ghost behavior...

Two cmdrs are configured as hidden users, with their Pictures folder pointing to the same Pictures folder of the 1st CMDR. This is always worked. I also checked for permissions, but all three cmdrs can write and modify to and, if I take a screenshot from ED, it appear in the intended folder.

EDDiscovery is watching at the correct journals location:

`[2017-03-22 12:41:59Z] Start Monitor on d:\Users\andrea\Saved Games\Frontier Developments\Elite Dangerous
[2017-03-22 12:41:59Z] Start Monitor on F:\Games\Saves\cmdr.b\Frontier Developments\Elite Dangerous
[2017-03-22 12:41:59Z] Start Monitor on F:\Games\Saves\cmdr.c\Frontier Developments\Elite Dangerous`

When I take a screenshots, it display always the same red error:

`Error in executing image conversion, try another screenshot, check output path settings. (Exception Object reference not set to an instance of an object.)`

After I take one screenshot, this is the log (for just one screenshot):

> [2017-03-22 12:42:29Z] Net tick exception : Object reference not set to an instance of an object.
> [2017-03-22 12:42:29Z]    at EDDiscovery.EliteDangerous.JournalEntry.FindEntry(JournalEntry ent, JObject entjo) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\JournalEntry.cs:line 915
> 
> [2017-03-22 12:42:29Z]    at EDDiscovery.EliteDangerous.MonitorWatcher.<>c.<ScanReader>b__11_0(JournalReaderEntry jre) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\EDJournalClass.cs:line 250
> 
> [2017-03-22 12:42:29Z]    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
> 
> [2017-03-22 12:42:29Z]    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
> 
> [2017-03-22 12:42:29Z]    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
> 
> [2017-03-22 12:42:29Z]    at EDDiscovery.EliteDangerous.MonitorWatcher.ScanReader(EDJournalReader nfi, List`1 entries) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\EDJournalClass.cs:line 274
> 
> [2017-03-22 12:42:29Z]    at EDDiscovery.EliteDangerous.MonitorWatcher.ScanForNewEntries() in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\EDJournalClass.cs:line 289
> [2017-03-22 12:42:31Z] Net tick exception : Object reference not set to an instance of an object.
> [2017-03-22 12:42:31Z]    at EDDiscovery.EliteDangerous.JournalEntry.FindEntry(JournalEntry ent, JObject entjo) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\JournalEntry.cs:line 915
> 
> [2017-03-22 12:42:31Z]    at EDDiscovery.EliteDangerous.MonitorWatcher.<>c.<ScanReader>b__11_0(JournalReaderEntry jre) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\EDJournalClass.cs:line 250
> 
> [2017-03-22 12:42:31Z]    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
> 
> [2017-03-22 12:42:31Z]    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
> 
> [2017-03-22 12:42:31Z]    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
> 
> [2017-03-22 12:42:31Z]    at EDDiscovery.EliteDangerous.MonitorWatcher.ScanReader(EDJournalReader nfi, List`1 entries) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\EDJournalClass.cs:line 274
> 
> [2017-03-22 12:42:31Z]    at EDDiscovery.EliteDangerous.MonitorWatcher.ScanForNewEntries() in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\EDJournalClass.cs:line 289
> [2017-03-22 12:42:33Z] Exception watcher: Object reference not set to an instance of an object.
> [2017-03-22 12:42:33Z] Trace:    at EDDiscovery2.ImageHandler.ImageConverter.GetOutputSubFolder() in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 828
> 
> [2017-03-22 12:42:33Z]    at EDDiscovery2.ImageHandler.ImageConverter.Convert() in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 664
> 
> [2017-03-22 12:42:33Z]    at EDDiscovery2.ImageHandler.ScreenshotDirectoryWatcher.ProcessScreenshot(String filename, String sysname, JournalScreenshot ss, Int32 cmdrid, ImageConverter cp) in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 592
> [2017-03-22 12:42:33Z] Error in executing image conversion, try another screenshot, check output path settings. (Exception Object reference not set to an instance of an object.)
> [2017-03-22 12:42:33Z] Net tick exception : Object reference not set to an instance of an object.
> [2017-03-22 12:42:33Z]    at EDDiscovery.EliteDangerous.JournalEntry.FindEntry(JournalEntry ent, JObject entjo) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\JournalEntry.cs:line 915
> 
> [2017-03-22 12:42:33Z]    at EDDiscovery.EliteDangerous.MonitorWatcher.<>c.<ScanReader>b__11_0(JournalReaderEntry jre) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\EDJournalClass.cs:line 250
> 
> [2017-03-22 12:42:33Z]    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
> 
> [2017-03-22 12:42:33Z]    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
> 
> [2017-03-22 12:42:33Z]    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
> 
> [2017-03-22 12:42:33Z]    at EDDiscovery.EliteDangerous.MonitorWatcher.ScanReader(EDJournalReader nfi, List`1 entries) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\EDJournalClass.cs:line 274
> 
> [2017-03-22 12:42:33Z]    at EDDiscovery.EliteDangerous.MonitorWatcher.ScanForNewEntries() in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\EDJournalClass.cs:line 289

What I really do not understand is that it was working, than suddenly stopped. This is not fixed yet...

**Comment by klightspeed** [comment]
This is multiple errors.

```
[2017-03-22 12:42:29Z] Net tick exception : Object reference not set to an instance of an object.
[2017-03-22 12:42:29Z] at EDDiscovery.EliteDangerous.JournalEntry.FindEntry(JournalEntry ent, JObject entjo) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\JournalEntry.cs:line 915

[2017-03-22 12:42:29Z] at EDDiscovery.EliteDangerous.MonitorWatcher.<>c.b__11_0(JournalReaderEntry jre) in C:\projects\eddiscovery\EDDiscovery\EliteDangerous\EDJournalClass.cs:line 250
```

The reader is returning null journal entries for some reason, and somehow not getting a NRE at line 87 of EDJournalReader

```
[2017-03-22 12:42:33Z] Exception watcher: Object reference not set to an instance of an object.
[2017-03-22 12:42:33Z] Trace: at EDDiscovery2.ImageHandler.ImageConverter.GetOutputSubFolder() in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 828

[2017-03-22 12:42:33Z] at EDDiscovery2.ImageHandler.ImageConverter.Convert() in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 664
```

Your branch is behind master.  Line 664 on master is:
```
                CommanderID = JournalScreenShot.CommanderId;            // reload in case GetScreenshot changed it..
```

**Comment by andreaspada** [comment]
Ok. I'll wait to the master branch include the correction on the "ghost behavior" - pull request #920 - than try with it.

Thanks!

**Comment by klightspeed** [comment]
I have rebased PR #920 onto master.

**Comment by andreaspada** [comment]
Well, it does not work yet. Gosh...

**Comment by andreaspada** [comment]
@finwen 
So, I'm try to narrowing down what could happens. I installed the last commit, #920, yet do not got my screenshots to work as intended. I checked all options: all them give error messages, but at least, if the Commander name is not involved, EDDiscovery convert the image and renames it. It also create sub-folders, if they do not have CMDR name included. So, this is not something related to folder permissions... almost certainly something went wrong during some Journal updating. I re-checked with a brand new Data folder, once more, at first using just one commander, as the default.

One of the tests give a new message, beside the common one (I think it was using the Date as subfolder...):

> [2017-03-22 15:36:50Z] Insufficient parameters supplied to the command
> [2017-03-22 15:36:50Z] Trace:    at System.Data.SQLite.SQLiteStatement.BindParameter(Int32 index, SQLiteParameter param)
> 
> [2017-03-22 15:36:50Z]    at System.Data.SQLite.SQLiteStatement.BindParameters()
> 
> [2017-03-22 15:36:50Z]    at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
> 
> [2017-03-22 15:36:50Z]    at System.Data.SQLite.SQLiteDataReader.NextResult()
> 
> [2017-03-22 15:36:50Z]    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
> 
> [2017-03-22 15:36:50Z]    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
> 
> [2017-03-22 15:36:50Z]    at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
> 
> [2017-03-22 15:36:50Z]    at EDDiscovery.DB.SQLiteCommandED`1.ExecuteNonQuery() in C:\projects\eddiscovery\EDDiscovery\DB\SQLiteCommandED.cs:line 533
> 
> [2017-03-22 15:36:50Z]    at EDDiscovery.DB.SQLiteDBClass.SQLNonQueryText(SQLiteConnectionED cn, DbCommand cmd) in C:\projects\eddiscovery\EDDiscovery\DB\SQLiteDBClass.cs:line 74
> 

I attached the last log, if can help.

[Trace_20170322152805.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/862512/Trace_20170322152805.0.txt)

**Comment by klightspeed** [comment]
3 errors in that trace.

Also, all of the options that errored out in that trace involve getting the commander's name.

PR 923 should fix the errors you are seeing.

**Comment by andreaspada** [comment]
Awesome. I'm building right now. I'll check ASAP...

**Comment by andreaspada** [comment]
FIXED!!!!!!! THANKS!!!!!!!!!!!!

**Pull request merged**
