### PR TITLE
Prevent runtime error when GetSystemsByName returns null

### PR DESCRIPTION
**Pull request by iainross**

### CODE REVIEW

**Comment by iainross** [comment]
Don't merge this yet, it was fine in code but since I've built it I'm suddenly seeing https://github.com/EDDiscovery/EDDiscovery/issues/1317 happening...

**Comment by iainross** [comment]
Deleted the last couple of journal files from my db and processed them again - it didn't recur.   Flew on for another bunch of systems against my local build and no recurrence.

I'm happy I've not introduced (or exposed) a systemic error but if anyone else wants to double check before this goes in that might not be a bad idea...

**Comment by iainross** [comment]
Oh FFS.  It was just waiting for me to post that comment before it started happening again.  I need to track this down before this can go in really.

**Comment by klightspeed** [comment]
Do the duplicate events have the same timestamp?  Need to check that it is properly matching the imported entries to the entries already in the history.

**Comment by iainross** [comment]
From journalentries table for one offending system I've got a StartJump at 2017-10-11 00:09:58Z and an FSD jump at 2017-10-11 00:10:17Z which are in the file and all is good.  But a second FSD jump is being inserted with a TravelLogId pointing back at a dummy TravelLogUnit for jumps synced from EDSM.

Since it's reliable in build, patchy in debug and the behaviour suggests that the local and remote records are, at least briefly, not agreeing it looks like there's some kind of timing thing going on where we're pushing the jump to EDSM from one place and seeing it on EDSM from another before that other place has caught up with the fact that we did actually push it so it thinks it's syncing back from EDSM (why those wrongly synced from EDSM jumps have no coordinates even though EDSM knows them may be a separate issue or it may not)

Bed time here, I'll look at it more tomorrow unless someone else spots it in the interim.

**Comment by klightspeed** [comment]
`GetSystemsByName` returning null means that the `api-v1/systems` API is returning an error.

<https://www.edsm.net/api-v1> does not mention anything about any rate limiting on the `api-v1/systems` API, though the X-Rate-Limit et al headers suggest it's 360 requests per hour.

**Pull request closed without merging**
