### PR TITLE
Resolved 1705 Scan Data on System -> Move Position of Approx Value

### PR DESCRIPTION
**Pull request by Heavensburn**
Hi,

https://github.com/EDDiscovery/EDDiscovery/issues/1705

Now resolved.

### CODE REVIEW

**Comment by robbyxp1** [comment]
I'm not sure what a flow panel brings to the party with WrapContents=false. Why did you use that? Why was it better than a standard panel.  I'm asking because we have had problems with the layout they bring previously, and all the other panels just use standard panels with fixed positions.. ;-)

**Comment by robbyxp1** [comment]
Actually, a RollUpPanel may be a much better solution, then that bit can be hidden if needed..

**Comment by Heavensburn** [comment]
Using Flow allowed me to collapse the horizontal such that:
image
Could be collapsed down to just the approx value:
image

But, I'll check out the RollUpPanel. Once I figure out how to get TestForm2 to compile and run. ;)

**Comment by Heavensburn** [comment]
Hope that's better. 
On open:
2018-02-17 10_42_53-eddiscovery version 9 1 6622 19229
If you right click and choose to close the controlsPanel, 'Approx Value' will move over:
2018-02-17 10_42_10-eddiscovery version 9 1 6622 19229
If you unpin, everything will collapse:
2018-02-17 10_42_24-eddiscovery version 9 1 6622 19229

**Pull request merged**
