### PR TITLE
Move EDSM journal discard list fetch to background

### PR DESCRIPTION
**Pull request by klightspeed**
This should fix an issue where a slow response from EDSM will cause the UI to freeze when Sync to EDSM is enabled.

### CODE REVIEW

**Comment by robbyxp1** [comment]
Good idea.

**Comment by robbyxp1** [comment]
Okay, but I have another suggestion. Why not just do the whole discard check, with time out, around here:

                        historyevent.Reset();
                        Action<string> logger = hqe.Logger;

                        List<HistoryEntry> hl = new List<HistoryEntry>() { first };

                        string logline = $"Adding {first.EntryType.ToString()} event to EDSM journal sync ({first.EventSummary})";
                        System.Diagnostics.Trace.WriteLine(logline);
                        //removed too verbose if (!manual)  hqe.Logger?.Invoke(logline);


Say just before making the list.. then its in the sync thread, does not change EDControllerMain...

**Comment by klightspeed** [comment]
I have now moved the reject list update into the EDSM sync thread, and added a check after dequeuing the event to check if it's on the reject list.

**Comment by robbyxp1** [comment]
Thanks.

**Pull request merged**
