### PR TITLE
Use concurrent dictionaries for StarScan

### LINKED ISSUE #1577: Unhandled UI exception error in 9.0.1 (Updated with more error messages)
### Description
Ferry trip from Deciat to Phoenix Harbour in Centralis (Colonia). Simple FSD jumps from waypoint to waypoint. Honking at every waypoint

### PR DESCRIPTION
**Pull request by iainross**
May fix #1577

### CODE REVIEW

**Comment by robbyxp1** [comment]
What's using this data multithreaded? I can't think of it off the top of my head ;-)

**Comment by iainross** [comment]
Background Worker/Refresh threads can create entries from journals, the UI thread can end up doing it if useEDSM == true in a call from any of the controls that ask for system data.

**Comment by robbyxp1** [comment]
Hmmm. I'll discord you on this.

**Comment by iainross** [comment]
k, I won't be on there until this evening.

**Comment by robbyxp1** [comment]
See discord again tonight when u get in

**Comment by robbyxp1** [comment]
I could not reproduce it.  And there is problems with the system cache as I stated in the discord. 

There is more involved to this than just this, we need to reinvent this whole part..

Closing for now.

**Pull request closed without merging**
