### PR TITLE
Cleanup a font handle leak in DownloadManagerForm

### PR DESCRIPTION
**Pull request by phroggster**

### CODE REVIEW

**Comment by robbyxp1** [comment]
i'll solve it in the current branch and merge back in thanks

**Comment by phroggster** [comment]
@klightspeed pointed out that I was disposing of this in the wrong spot. I know you said that you were going to move this to `OnFormClosing()` or something, but if it stays in `Dispose(boolean)` make sure that said boolean is `true`, and that it must not be limited inside an `if (components != null)` check. Here's what it should *really* look like if *everything* is properly accounted for:

```CS
public void Dispose(bool disposing) {
  if (disposing) {
    components?.Dispose();
    font?.Dispose();
  }
  base.Dispose(disposing);
  GC.SuppressFinalize(this);
}
```

**Comment by klightspeed** [comment]
I think the base class (which implements the parameterless `Dispose()` method would already do `GC.SuppressFinalize(this)`

**Comment by phroggster** [comment]
Oy. Now you've got me mixing up my dispose patterns. 😃

**Comment by phroggster** [comment]
I've pushed a corrected version of this one, again, just for my sanity or if we want a new release before other options get in.

**Pull request merged**
